name: HaxeFlixel CI

# Controls when the workflow will runon: [push, pull_request]
on: [push, pull_request]


  push:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Setup Haxe

        uses: HaxeFoundation/setup-haxe@v1.4.3

        with:

          haxe-version: 4.1.5

      - name: Setup Lime

        run: haxelib git lime https://github.com/openfl/lime.git 7.9.0

        working-directory: ${{ github.workspace }}

      - name: Setup OpenFL

        run: haxelib install openfl 9.1.0

        working-directory: ${{ github.workspace }}

      - name: Setup HaxeFlixel

        run: haxelib install flixel 4.9.0

        working-directory: ${{ github.workspace }}

      - name: Setup flixel-tools

        run: haxelib install flixel-tools 1.9.0

        working-directory: ${{ github.workspace }}

      - name: Setup flixel-ui

        run: haxelib install flixel-ui 2.5.0

        working-directory: ${{ github.workspace }}

      - name: Setup hscript

        run: haxelib install hscript 2.4.0

        working-directory: ${{ github.workspace }}

      - name: Setup flixel-addons

        run: haxelib install flixel-addons 2.7.0

        working-directory: ${{ github.workspace }}

      - name: Setup actuate

        run: haxelib install actuate 1.8.9

        working-directory: ${{ github.workspace }}

      - name: Setup linc_luajit

        run: haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git

        working-directory: ${{ github.workspace }}

      - name: Setup hxvm-luajit

        run: haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

        working-directory: ${{ github.workspace }}

      - name: Setup faxe

        run: haxelib git faxe https://github.com/uhrobots/faxe

        working-directory: ${{ github.workspace }}

      - name: Setup polymod

        run: haxelib git polymod https://github.com/MasterEric/polymod.git

        working-directory: ${{ github.workspace }}

      - name: Setup discord_rpc

        run: haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git

        working-directory: ${{ github.workspace }}

      - name: Setup extension-webm

        run: haxelib git extension-webm https://github.com/KadeDev/extension-webm.git

        working-directory: ${{ github.workspace }}

      - name: Build for ${{ matrix.os }}

        run: lime build

