name: Friday Night Funkin' Build with Kade Engine

  workflow_dispatch:
  
# Controls when the workflow will run
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Haxe
        run: sudo apt-get install haxe=4.1.5
      - name: Install HaxeFlixel
        run: haxelib install flixel
      - name: Install Git
        run: sudo apt-get install git
      - name: Install Libraries
        run: |
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons
          haxelib install actuate
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib run flixel-tools setup
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          lime rebuild extension-webm windows
      - name: Build for Windows
        if: runner.os == 'windows'
        run: lime build windows
      - name: Build for macOS
        if: runner.os == 'macos'
        run: lime build mac
      - name: Build for Linux
        if: runner.os == 'linux'
        run: lime build linux
      - name: Build for HTML5
        run: lime build html5
      - name: Archive Builds
        run: |
          zip -r "windows.zip" "export/release/windows/bin"
          zip -r "mac.zip" "export/release/mac/bin"
          zip -r "linux.zip" "export/release/linux/bin"
          zip -r "html5.zip" "export/release/html5/bin"
        if: success()
      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: Builds
          path: |
            windows.zip
            mac.zip
            linux.zip
            html5.zip
